Test gradle build workflow (cont'd)

diff --git a/.github/workflows/spring-boot-ci.yml b/.github/workflows/spring-boot-ci.yml
--- a/.github/workflows/spring-boot-ci.yml
+++ b/.github/workflows/spring-boot-ci.yml
@@ -17,6 +17,12 @@ jobs:
           java-version: '17'
           distribution: 'adopt'
 
+      - name: Configure Google Cloud SDK repository
+        run: |
+          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
+          sudo apt-get update
+
       - name: Install/Update Google Cloud SDK
         run: |
           if ! gcloud --version; then
@@ -29,7 +35,10 @@ jobs:
             echo "Google Cloud SDK already installed. Updating..."
             sudo apt-get update && sudo apt-get upgrade google-cloud-sdk
           fi
-      
+
+      - name: Verify Google Cloud SDK Installation
+        run: |
+          gcloud --version || echo "Google Cloud SDK not found"
 
       - name: Authenticate with Google Cloud
         env:
